loki:
  commonConfig:
    replication_factor: 1
  limits_config:
    reject_old_samples: false
    reject_old_samples_max_age: 720h
    ingestion_rate_mb: 20
    ingestion_burst_size_mb: 30
    allow_structured_metadata: true
    volume_enabled: true
  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
      endpoint: http://192.168.30.145:9000
      region: us-east-1
      #access_key_id: ${S3_ACCESS_KEY} 
      #secret_access_key: ${S3_SECRET_KEY}
      s3ForcePathStyle: true
      insecure: true 
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
    enabled: true
  ruler:
    enable_api: true
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.30.207

minio:
  enabled: false
      
deploymentMode: SingleBinary
singleBinary:
  replicas: 1
  extraArgs:
      - "-ingester.unordered-writes=true"
      - "-validation.reject-old-samples=false"
  extraEnvFrom:
    - secretRef:
        name: minio-credentials
  extraEnv:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: minio-credentials
          key: S3_ACCESS_KEY
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-credentials
          key: S3_SECRET_KEY
    - name: S3_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-credentials
          key: S3_ACCESS_KEY
    - name: S3_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: minio-credentials
          key: S3_SECRET_KEY

service:
  type: LoadBalancer
  loadBalancerIP: 192.168.30.206

gateway:
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.30.206

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0