# values.yaml for Grafana Agent/Alloy
controller:
  type: statefulset

agent:
  mode: flow
  extraArgs:
    - "--disable-reporting"
  hostAliases:
    - ip: "192.168.30.20"
      hostnames:
        - "ubuntu-k8s"
    - ip: "192.168.30.21"
      hostnames:
        - "ubuntu-k8s-2"
    - ip: "192.168.30.22"
      hostnames:
        - "ubuntu-k8s-3"
    - ip: "192.168.30.23"
      hostnames:
        - "ubuntu-k8s-4"
    - ip: "192.168.30.24"
      hostnames:
        - "ubuntu-k8s-5"
    - ip: "192.168.30.25"
      hostnames:
        - "ubuntu-k8s-6"
    - ip: "192.168.30.26"
      hostnames:
        - "ubuntu-k8s-6"
  configMap:
    create: true
    content: |
      logging {
        level  = "info"
        format = "logfmt"
      }
      
      discovery.kubernetes "pods" {
        role = "pod"
      }
      
      discovery.relabel "pod_metadata" {
        targets = discovery.kubernetes.pods.targets
        
        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          action = "replace"
          target_label = "namespace"
        }
        
        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          action = "replace"
          target_label = "pod"
        }
        
        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          action = "replace"
          target_label = "container"
        }
        
        rule {
          source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
          action = "replace"
          target_label = "app"
        }
        
        rule {
          source_labels = ["__meta_kubernetes_pod_controller_name"]
          target_label = "deployment"
        }
      }
      
      loki.source.kubernetes "pods" {
        targets = discovery.relabel.pod_metadata.output
        forward_to = [loki.write.local.receiver]
      }
      
      loki.write "local" {
        endpoint {
          url = "http://grafana-loki.grafana-loki.svc.cluster.local:3100/loki/api/v1/push"
          tenant_id = "fake"
        }
      }
