# values.yaml for Grafana Agent
controller:
  type: statefulset

agent:
  mode: flow
  configMap:
    create: true
    content: |
      logging {
        level  = "info"
        format = "logfmt"
      }
      
      discovery.kubernetes "pods" {
        role = "pod"
      }
      
      loki.source.kubernetes "pods" {
        targets    = discovery.kubernetes.pods.targets
        forward_to = [loki.write.local.receiver]
      }
      
      loki.write "local" {
        endpoint {
          url = "http://grafana-loki.grafana-loki.svc.cluster.local:3100/loki/api/v1/push"
          tenant_id = "fake"
          headers = {
            "X-Scope-OrgID" = "fake"
          }
        }
        external_labels = {
          cluster = "personal-k8s"
          job = "kubernetes-pods"
        }
      }