# values.yaml for Grafana Agent
controller:
  type: statefulset

agent:
  mode: flow
  configMap:
    create: true
    content: |
      logging {
        level  = "info"
        format = "logfmt"
      }
      
      discovery.kubernetes "pods" {
        role = "pod"
      }
      
      loki.source.kubernetes "pods" {
        targets    = discovery.kubernetes.pods.targets
        forward_to = [loki.write.local.receiver]
      }
      
      loki.write "local" {
        endpoint {
          url = "http://grafana-loki-gateway.grafana-loki.svc.cluster.local/loki/api/v1/push"
        }
      }