# values.yaml for Grafana Agent/Alloy
controller:
  type: statefulset

agent:
  mode: flow
  extraArgs:
    - "--disable-reporting"
  configMap:
    create: true
    content: |
      logging {
        level  = "info"
        format = "logfmt"
      }
      
      discovery.kubernetes "pods" {
        role = "pod"
      }
      
      discovery.relabel "pod_metadata" {
        targets = discovery.kubernetes.pods.targets
        
        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          action = "replace"
          target_label = "namespace"
        }
        
        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          action = "replace"
          target_label = "pod"
        }
        
        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          action = "replace"
          target_label = "container"
        }
        
        rule {
          source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
          action = "replace"
          target_label = "app"
        }
        
        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          regex = "^(.*)-[a-z0-9]+-[a-z0-9]+$"
          replacement = "$1"
          target_label = "deployment"
        }
      }
      
      loki.source.kubernetes "pods" {
        targets = discovery.relabel.pod_metadata.output
        forward_to = [loki.write.local.receiver]
      }
      
      loki.write "local" {
        endpoint {
          url = "http://grafana-loki.grafana-loki.svc.cluster.local:3100/loki/api/v1/push"
          tenant_id = "fake"
        }
      }