# logging:
#   image:
#     registry: ""
#     repository: ""
#     tag: 

agent:
  # image:
  #   repository: ""
  #   pullPolicy: Always
  #   tag: ""
  
  pullSecrets: []
    #- regcred
  
  resourceClasses:
    logan/container-runner:
      spec:
        terminationGracePeriodSeconds: 18300 # 5 minutes
        containers:
          - resources:
              limits:
                cpu: 1500m
                memory: 2Gi
                ephemeral-storage: "10Gi"
              requests:
                cpu: 1500m
                memory: 2Gi
                ephemeral-storage: "10Gi"
        imagePullSecrets:
          - name: regcred
        nodeSelector:
          ci: "true" 
        tolerations:
          - key: "ci-workload"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
    imlogang-organization/container-runner:
      spec:
        terminationGracePeriodSeconds: 18300 # 5 minutes
        containers:
          - resources:
              limits:
                cpu: 1500m
                memory: 2Gi
                ephemeral-storage: "10Gi"
              requests:
                cpu: 1500m
                memory: 2Gi
                ephemeral-storage: "10Gi"
        nodeSelector:
          ci: "true" 
        tolerations:                    # Add tolerations section
          - key: "ci-workload"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
  customSecret: logan.container-runner

  ssh:
    enabled: true
    controllerName: "gateway.envoyproxy.io/gatewayclass-controller"
    parametersRef: {}
    startPort: 54782
    numPorts: 20
