agent:
  #image:
  #  tag: "kubernetes-experimental"
  resourceClasses:
    logan/container-runner:
      spec:
        terminationGracePeriodSeconds: 18300 # 5 minutes
        containers:
          - resources:
              limits:
                cpu: 1500m
                memory: 2Gi
                ephemeral-storage: "10Gi"
              requests:
                cpu: 1500m
                memory: 2Gi
                ephemeral-storage: "10Gi"
          - livenessProbe:
              initialDelaySeconds: 250
              periodSeconds: 35
              timeoutSeconds: 20
              successThreshold: 1
              failureThreshold: 6
            lifecycle:
              preStop:
                exec:
                  command: 
                    - /bin/bash
                    - -c
                    - >
                      echo 'PreStop hook: Delaying termination for 60 seconds' &&
                      sleep 60 &&
                      echo 'PreStop hook: Sending TERM signal to process 1' &&
                      kill 1
        nodeSelector:
          ci: "true" 
        imagePullSecrets:
          - name: "aws-secret"
        tolerations:
          - key: "ci-workload"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
    imlogang-organization/container-runner:
      spec:
        terminationGracePeriodSeconds: 18300 # 5 minutes
        containers:
          - resources:
              limits:
                cpu: 1500m
                memory: 2Gi
                ephemeral-storage: "10Gi"
              requests:
                cpu: 1500m
                memory: 2Gi
                ephemeral-storage: "10Gi"
        nodeSelector:
          ci: "true" 
        imagePullSecrets:
          - name: "aws-secret"
        tolerations:                    # Add tolerations section
          - key: "ci-workload"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
  customSecret: logan.container-runner
  
  # serviceAccount:
  #   annotations:
  #     eks.amazonaws.com/role-arn: arn:aws:iam::397187125081:role/cci-iam
  #   name: kaniko-test
  # podAnnotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::397187125081:role/cci-iam
  # image:
  #   registry: ""
  #   repository: "circleci/runner-agent"
  #   pullPolicy: Always
  #   tag: "kubernetes-edge"
  #   digest: ""

  ssh:
    enabled: true
    controllerName: "gateway.envoyproxy.io/gatewayclass-controller"
    parametersRef: {}
    startPort: 54782
    numPorts: 20

orchestrator:
  image:
    registry: "dockerregistry.logangodsey.com"
    repository: "task-agent-server-4.6"
    tag: "latest"