agent:
  resourceClasses:
    logan/container-runner:
      spec:
        terminationGracePeriodSeconds: 300 # 5 minutes
        containers:
          - livenessProbe:
              initialDelaySeconds: 250
              periodSeconds: 35
              timeoutSeconds: 20
              successThreshold: 1
              failureThreshold: 6
            lifecycle:
              preStop:
                exec:
                  command: 
                    - /bin/bash
                    - -c
                    - >
                      echo 'PreStop hook: Delaying termination for 60 seconds' &&
                      sleep 60 &&
                      echo 'PreStop hook: Sending TERM signal to process 1' &&
                      kill 1
        imagePullSecrets:
          - name: "aws-secret"
    imlogang-organization/container-runner:
  customSecret: logan.container-runner
  
  # serviceAccount:
  #   annotations:
  #     eks.amazonaws.com/role-arn: arn:aws:iam::397187125081:role/cci-iam
  #   name: kaniko-test
  # podAnnotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::397187125081:role/cci-iam
  # image:
  #   registry: ""
  #   repository: "circleci/runner-agent"
  #   pullPolicy: Always
  #   tag: "kubernetes-edge"
  #   digest: ""

  ssh:
    enabled: true
    controllerName: "gateway.envoyproxy.io/gatewayclass-controller"
    parametersRef: {}
    startPort: 54782
    numPorts: 20