agent:
  #image:
  #  tag: "kubernetes-experimental"
  resourceClasses:
    imlogang-organization-server/container-runner-server:
      spec:
        containers:
          - resources:
              limits:
                cpu: 2000m
                memory: 4Gi
                ephemeral-storage: "5Gi"
              requests:
                cpu: 1500m
                memory: 2Gi
                ephemeral-storage: "5Gi"
        nodeSelector:
          ci: "true"  
        tolerations:                    # Add tolerations section
          - key: "ci-workload"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
    imlogang-organization-server/small:
      spec:
        containers:
          - resources:
              limits:
                cpu: 2000m
                memory: 4Gi
                ephemeral-storage: "10Gi"
              requests:
                cpu: 2000m
                memory: 4Gi
                ephemeral-storage: "10Gi"
        nodeSelector:
          ci: "true"  
        tolerations:
          - key: "ci-workload"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
    imlogang-organization-server/medium:
      spec:
        containers:
          - resources:
              limits:
                cpu: 4000m
                memory: 8Gi
                ephemeral-storage: "10Gi"
              requests:
                cpu: 4000m
                memory: 8Gi
                ephemeral-storage: "10Gi"
        nodeSelector:
          ci: "true"  
        tolerations:
          - key: "ci-workload"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
  customSecret: logan.container-runner-server
  runnerAPI: https://cciserver.logangodsey.com

  ssh:
    enabled: true
    controllerName: "gateway.envoyproxy.io/gatewayclass-controller"
    parametersRef: {}
    startPort: 54782
    numPorts: 20

  orchestrator:
    image:
      registry: "https://dockerregistry.logangodsey.com/"
      repository: "task-agent-server-4.6"
      tag: "latest"