agent:
  #image:
  #  tag: "kubernetes-experimental"
  resourceClasses:
    imlogang-organization-server/container-runner-server:
      spec:
        terminationGracePeriodSeconds: 300 # 5 minutes
        containers:
          - resources:
              limits:
                cpu: 2000m
                memory: 4Gi
                ephemeral-storage: "5Gi"
              requests:
                cpu: 1500m
                memory: 2Gi
                ephemeral-storage: "5Gi"
  customSecret: logan.container-runner-server
  runnerAPI: https://cciserver.logangodsey.com
  


  ssh:
    enabled: true
    controllerName: "gateway.envoyproxy.io/gatewayclass-controller"
    parametersRef: {}
    startPort: 54782
    numPorts: 20