agent:
  resourceClasses:
    imlogang-organization-server/container-runner-server:
  customSecret: logan.container-runner-server
  runnerAPI: https://cciserver.logangodsey.com
  


  ssh:
    enabled: true
    controllerName: "gateway.envoyproxy.io/gatewayclass-controller"
    parametersRef: {}
    startPort: 54782
    numPorts: 20