version: 2.1 

parameters:
  prod:
    default: false
    type: boolean
  stage:
    default: false
    type: boolean
  container-runner-cloud:
    default: false
    type: boolean
  container-runner-server:
    default: false
    type: boolean
  circleci-release-agent-system:
    default: false
    type: boolean
  namespace:
    default: ""
    type: string
  file-path:
    default: ""
    type: string
  

commands:
  managed-namespace:
    steps:
      - run: 
          name: make sure namespace managed
          command: |
            cd << pipeline.parameters.file-path >>
            terraform import kubernetes_namespace.<< pipeline.parameters.namespace >> << pipeline.parameters.namespace >>

  terraform-plan:
    steps:
      - run: 
          name: terraform plan
          command: |
            cd << pipeline.parameters.file-path >>
            terraform plan -out plan.tf
  terraform-init:
    steps:
      - run:
          name: terraform init
          command: |
            cd << pipeline.parameters.file-path >>
            terraform init
            
  envvar-prod:
    steps:
      - run:
          name: echo envvars for prod
          command: |
            echo 'export TF_VAR_client_id="'"${CLIENT_ID}"'"' >> "$BASH_ENV"
            echo 'export TF_VAR_beemoviebot="'"${BEEMOVIEBOT}"'"' >> "$BASH_ENV"
            echo 'export TF_VAR_pterotoken="'"${PteroToken}"'"' >> "$BASH_ENV"
  
  envvar-stage:
    steps:
      - run:
          name: echo envvars for staging
          command: |
            echo 'export TF_VAR_client_id="'"${CLIENT_ID_STAGING}"'"' >> "$BASH_ENV"
            echo 'export TF_VAR_beemoviebot="'"${BEEMOVIEBOT_STAGING}"'"' >> "$BASH_ENV"
            echo 'export TF_VAR_pterotoken="'"${PteroToken}"'"' >> "$BASH_ENV"
  
  cloud-container-runner:
      steps:
        - run:
            name: echo envvars for cloud container runner
            command: |
              echo 'export TF_VAR_imlogang_organization_container_runner="'"${IMLOGANG_CONTAINER_RUNNER}"'"' >> "$BASH_ENV"
              echo 'export TF_VAR_logan_container_runner="'"${LOGAN_CONTAINER_RUNNER}"'"' >> "$BASH_ENV"
  container-runner-server:
      steps:
        - run:
            name: echo envvars for server container runner
            command: |
              echo 'export TF_VAR_imlogang_organization_container_runner_server="'"${IMLOGANG_CONTAINER_RUNNER_SERVER}"'"' >> "$BASH_ENV"
              
  circleci-release-agent-system:
      steps:
        - run:
            name: echo envvars for server container runner
            command: |
              echo 'export TF_VAR_circleci_release_agent_system_token="'"${CIRCLECI_RELEASE_AGENT_TOKEN}"'"' >> "$BASH_ENV"
              
jobs:
  terraform-plan-prod:
    machine: true 
    resource_class: imlogang-organization-server/ubuntu-k8s
    steps:
      - checkout
      - envvar-prod
      - terraform-init
      - managed-namespace
      - terraform-plan
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform-plan-stage:
    machine: true 
    resource_class: imlogang-organization-server/ubuntu-k8s
    steps:
      - checkout
      - envvar-stage
      - terraform-init
      - managed-namespace
      - terraform-plan
      - persist_to_workspace:
          root: .
          paths:
            - .
    
  terraform-plan-container-runner-cloud:
    machine: true 
    resource_class: imlogang-organization-server/ubuntu-k8s
    steps:
      - checkout
      - cloud-container-runner
      - terraform-init
      - managed-namespace
      - terraform-plan
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform-plan-container-runner-server:
    machine: true 
    resource_class: imlogang-organization-server/ubuntu-k8s
    steps:
      - checkout
      - container-runner-server
      - terraform-init
      - managed-namespace
      - terraform-plan
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform-circleci-release-agent-system:
    machine: true 
    resource_class: imlogang-organization-server/ubuntu-k8s
    steps:
      - checkout
      - circleci-release-agent-system
      - terraform-init
      - managed-namespace
      - terraform-plan
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform-apply:
    machine: true
    resource_class: imlogang-organization-server/ubuntu-k8s
    steps:
      - envvar-prod
      - attach_workspace:
          at: .
      - run:
          name: terraform apply
          command: |
            cd << pipeline.parameters.file-path >>
            terraform apply -auto-approve "plan.tf"

workflows:
  terraform-beemoviebot-prod:
    when: << pipeline.parameters.prod >>
    jobs:
      - terraform-plan-prod:
          context:
            - kubeconfig
            - beemoviebot
      - terraform-apply:
          requires:
            - terraform-plan-prod
          context:
            - kubeconfig
            - beemoviebot
          
  terraform-beemoviebot-stage:
    when: << pipeline.parameters.stage >>
    jobs:
      - terraform-plan-stage:
          context:
            - kubeconfig
            - beemoviebot
      - terraform-apply:
          requires:
            - terraform-plan-stage
          context:
            - kubeconfig
            - beemoviebot
  
  terraform-cloud-container-runner:
    when: << pipeline.parameters.container-runner-cloud >>
    jobs:
      - terraform-plan-container-runner-cloud:
          context:
            - kubeconfig
            - container-runner-cloud
      - terraform-apply:
          requires:
            - terraform-plan-container-runner-cloud
          context:
            - kubeconfig
            - container-runner-cloud
  
  terraform-server-container-runner:
    when: << pipeline.parameters.container-runner-server >>
    jobs:
      - terraform-plan-container-runner-server:
          context:
            - kubeconfig
            - container-runner-server
      - terraform-apply:
          requires:
            - terraform-plan-container-runner-server
          context:
            - kubeconfig
            - container-runner-server
  
  terraform-circleci-release-agent-system:
    when: << pipeline.parameters.circleci-release-agent-system >>
    jobs:
      - terraform-plan-circleci-release-agent-system:
          context:
            - kubeconfig
            - circleci-release-agent-system
      - terraform-apply:
          requires:
            - terraform-plan-circleci-release-agent-system
          context:
            - kubeconfig
            - circleci-release-agent-system