tempo:
  searchEnabled: true
  storage:
    trace:
      backend: s3
      s3:
        #access_key: ${AWS_ACCESS_KEY_ID}
        #secret_key: ${AWS_SECRET_ACCESS_KEY}
        bucket: tempo-traces
        endpoint: 192.168.30.145:9000
        insecure: true
        region: us-east-1

extraEnv:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: minio-credentials
        key: S3_ACCESS_KEY
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: minio-credentials
        key: S3_SECRET_KEY

extraArgs:
  - "-log.level=debug"

service:
  type: LoadBalancer
  # Optional: specify IP if you want a specific one
  loadBalancerIP: 192.168.30.207

persistence:
  enabled: false

serviceMonitor:
  enabled: false