tempo:
  searchEnabled: true
  storage:
    trace:
      backend: s3
      s3:
        #access_key_id: ${S3_ACCESS_KEY}
        #secret_access_key: ${S3_SECRET_KEY}
        bucket: tempo-traces
        endpoint: http://192.168.30.145:9000
        insecure: true

extraEnv:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: minio-credentials
        key: S3_ACCESS_KEY
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: minio-credentials
        key: S3_SECRET_KEY

extraArgs:
  - "-config.expand-env=true"

service:
  type: LoadBalancer
  # Optional: specify IP if you want a specific one
  loadBalancerIP: 192.168.30.207/24



persistence:
  enabled: false

serviceMonitor:
  enabled: false