authentik:
  secret_key: "PleaseGenerateASecureKey"
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to sentry.io, and is fully opt-in
  error_reporting:
    enabled: false
  postgresql:
    password: "ThisIsNotASecurePassword"

server:
  ingress:
    # Specify kubernetes ingress controller class name
    ingressClassName: kong
    enabled: true
    hosts:
      - "authentik.logangodsey.com"
    paths:
      - /
    pathType: Prefix
    tls: []
      # - hosts:
      #     - authentik.logangodsey.com
      #   secretName: authentik-tls-cert

postgresql:
  enabled: true
  auth:
    password: "ThisIsNotASecurePassword"
redis:
  enabled: true