authentik:
  secret_key: "PleaseGenerateASecureKey"
  error_reporting:
    enabled: false
  postgresql:
    password: "ThisIsNotASecurePassword"
  env:
    AUTHENTIK_PROXY__EXTERNAL_HOST: https://authentik.logangodsey.com
    AUTHENTIK_PROXY__TRUST_X_FORWARDED_PROTO: "true"
    AUTHENTIK_CSRF__TRUSTED_ORIGINS: https://authentik.logangodsey.com

# Configure server to use LoadBalancer with specific IP
server:
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.30.206  # Specify the exact IP you want
    annotations:
      # You can also use the annotation method if preferred
      metallb.universe.tf/loadBalancerIPs: 192.168.30.206

# Database and cache must be enabled
postgresql:
  enabled: true
  auth:
    password: "ThisIsNotASecurePassword"
redis:
  enabled: true