apiVersion: v1
kind: ConfigMap
metadata:
  name: kong
  namespace: kong
data:
  kong.yml: |
    _format_version: "3.0"
    services:
    - name: go-api-service
      url: http://go-api-service.go-api.svc.cluster.local:8080
      routes:
      - name: go-api-service-routes
        paths:
          - /
          - /hello
        methods:
          - GET
