apiVersion: v1
kind: ConfigMap
metadata:
  name: kong
  namespace: kong
data:
  kong.yml: |
    _format_version: "2.1"
    services:
      - name: go-api-service
        url: http://go-api-service.go-api.svc.cluster.local:8080
        routes:
        - name: website
          paths:
            - /
          methods:
            - GET
