ingressController:
  enabled: true
  env:
    - name: KONG_DECLARATIVE_CONFIG
      value: "/etc/kong/kong.yml"
  volumeMounts:
    - name: kong-config
      mountPath: /etc/kong/kong.yml
      subPath: kong.yml
  volumes:
    - name: kong-config
      configMap:
        name: kong

kong:
  database: off
  proxy:
    externalIPs:
      - 192.168.30.203
  userDefinedVolumes:
    - name: kong
      configMap:
        name: kong
  userDefinedVolumeMounts:
    - name: kong
      mountPath: /etc/kong/kong.yml
      subPath: kong.yml

env:
  DECLARATIVE_CONFIG: "/etc/kong/kong.yml"

admin:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false

service:
  type: LoadBalancer
  externalIPs:
    - 192.168.30.203

dblessConfig:
  configMap: "kong"

extraConfigMaps:
  - name: kong
    mountPath: /etc/kong/
    subPath: kong.yml