ingressController:
  enabled: false

kong:
  database: off
  proxy:
    externalIPs:
      - 192.168.30.203

admin:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false

service:
  type: LoadBalancer
  externalIPs:
    - 192.168.30.203

dblessConfig:
  config: |
    _format_version: "3.0"
    services:
      - name: web-ui
        protocol: http
        host: web-ui.web-ui.svc.cluster.local
        port: 80
        routes:
          - name: website
            paths:
              - /
              - /resume
              - /blog
            strip_path: false
            hosts: 
              - logangodsey.com
              - www.logangodsey.com

      - name: go-api-service-internal
        protocol: http
        host: go-api-service.go-api.svc.cluster.local
        port: 8080 
        routes:
          - name: api_internal
            paths:
              - /api/private/list_tables
            strip_path: false
            hosts:
              - api-service.logangodsey.com
            # plugins:
            #   - name: ip-restriction
            #     config:
            #       allow: 
            #         - 192.168.30.0/24

      - name: authentik
        protocol: http
        host: authentik-server.authentik.svc.cluster.local
        port: 80
        routes:
          - name: main routes
            paths:
              - /
              - /auth
            strip_path: false
            hosts:
              - www.authentik.logangodsey.com
              - authentik.logangodsey.com