ingressController:
  enabled: true
  installCRDs: false
  configMap: kong
  config:
    name: kong

kong:
  database: off
  proxy:
    externalIPs:
      - 192.168.30.205
  admin:
    enabled: false

service:
  type: LoadBalancer
  externalIPs:
    - 192.168.30.205

# Reference the custom ConfigMap you created with Terraform
plugins:
  configMaps:
    - pluginName: custom-plugin
      name: kong  # This should match the ConfigMap name
      subdirectories:
        - name: kong
          path: config