ingressController:
  enabled: false

deployment: 
  kong:
    database: off
    proxy:
      externalIPs:
        - 192.168.30.203

admin:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false

service:
  type: LoadBalancer
  externalIPs:
    - 192.168.30.203

dblessConfig:
  configMap: "kong"

extraConfigMaps:
  configMap: kong