ingressController:
  enabled: true
  installCRDs: false
  configMap: kong
  config:
    name: kong

kong:
  database: off
  proxy:
    externalIPs:
      - 192.168.30.203
  deployment:
    kong:
      userDefinedVolumes:
        - name: kong
          configMap:
            name: kong
      userDefinedVolumeMounts:
        - name: kong
          mountPath: /etc/kong/

admin:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false

service:
  type: LoadBalancer
  externalIPs:
    - 192.168.30.203

dblessConfig:
  configMap: "kong"

extraConfigMaps:
  - name: kong
    mountPath: /etc/kong/