ingressController:
  enabled: true
  installCRDs: false
  configMap: kong
  config:
    name: kong

kong:
  database: off
  proxy:
    externalIPs:
      - 192.168.30.203

admin:
  enabled: true
  type: LoadBalancer  # Or NodePort depending on your needs
  servicePort: 8444
  serviceProtocol: http
  http:
    enabled: true  # Set this to false to disable HTTP access
  tls:
    enabled: false  # Set this to true to enable TLS (HTTPS) for admin access

service:
  type: LoadBalancer
  externalIPs:
    - 192.168.30.203

# Reference the custom ConfigMap you created with Terraform
plugins:
  configMaps:
    - pluginName: custom-plugin
      name: kong  # This should match the ConfigMap name
      subdirectories:
        - name: kong
          path: config
