ingressController:
  enabled: false

kong:
  database: off
  proxy:
    externalIPs:
      - 192.168.30.203

admin:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false

service:
  type: LoadBalancer
  externalIPs:
    - 192.168.30.203

dblessConfig:
  config: |
    _format_version: "3.0"
    services:
      - name: go-api-service
        protocol: http
        host: go-api-service.go-api.svc.cluster.local
        port: 8080 
        routes:
          - name: website
            paths:
              - /
              - /resume
              - /blog
            strip_path: false
            hosts: 
              - logangodsey.com
              - www.logangodsey.com
          - name: hello_api
            paths:
              - /hello
            hosts: 
              - logangodsey.com
              - www.logangodsey.com
            strip_path: false

      - name: go-api-service-internal
        protocol: http
        host: go-api-service.go-api.svc.cluster.local
        port: 8080 
        routes:
          - name: api_internal
            paths:
              - /swagger/
              - /swagger/swagger.json
              - /api/private/list_tables
              - /api/private/create_table
              - /api/private/delete_table
            strip_path: false
            hosts:
              - api-service.logangodsey.com
            # plugins:
            #   - name: ip-restriction
            #     config:
            #       allow: 
            #         - 192.168.30.0/24