ingressController:
  enabled: true
  installCRDs: false
  configMap: kong
  config:
    name: kong

kong:
  database: off
  proxy:
    externalIPs:
      - 192.168.30.205

admin:
  enabled: true
  type: LoadBalancer  # Or NodePort depending on your needs
  servicePort: 8001   # Admin API should listen on port 8001
  serviceProtocol: http  # HTTP protocol for Admin API (since TLS is not needed)
  
  # Enable HTTP access (port 8001) for admin
  http:
    enabled: true  # Keep HTTP enabled for admin access
  tls:
    enabled: false  # Disable TLS (HTTPS) for admin access since it's not required

service:
  type: LoadBalancer
  externalIPs:
    - 192.168.30.203

# Reference the custom ConfigMap you created with Terraform
plugins:
  configMaps:
    - pluginName: custom-plugin
      name: kong  # This should match the ConfigMap name
      subdirectories:
        - name: kong
          path: config
