ingressController:
  enabled: false

kong:
  database: off
  proxy:
    externalIPs:
      - 192.168.30.203

admin:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false

service:
  type: LoadBalancer
  externalIPs:
    - 192.168.30.203

dblessConfig:
  config: |
    _format_version: "3.0"
    services:
    - name: status
      url: localhost:8001
      routes:
      - name: status
        paths:
        - /status

    - name: go-api-service
      url: go-api-service.go-api.svc.cluster.local:8080
      routes:
      - name: website
        paths:
        - /
      - name: hello_api
        paths:
        - /hello
      strip_path: false