ingressController:
  enabled: true
  installCRDs: false
  configMap: kong-config  # Default ConfigMap; if you're using a custom one, update this line.
  config:
    name: kong-config

kong:
  database: off
  proxy:
    externalIPs:
      - 192.168.30.205

service:
  type: LoadBalancer
  externalIPs:
    - 192.168.30.205

# Reference the custom ConfigMap you created with Terraform
plugins:
  configMaps:
    - pluginName: custom-plugin
      name: kong.yml  # This should match the ConfigMap name
      subdirectories:
        - name: kong.yml
          path: config