ingressController:
  enabled: false

kong:
  database: off
  proxy:
    externalIPs:
      - 192.168.30.203
  volumes:
  - name: kong-config
    configMap:
      name: kong
  volumeMounts:
  - name: kong-config
    mountPath: /etc/kong
    subPath: kong.yml

admin:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false

service:
  type: LoadBalancer
  externalIPs:
    - 192.168.30.203

dblessConfig:
  configMap: "kong"

extraConfigMaps:
  configMap: kong