ingressController:
  enabled: true
  installCRDs: false
  configMap: kong
  config:
    name: kong

kong:
  database: off
  proxy:
    externalIPs:
      - 192.168.30.203
  userDefinedVolumes:
    - name: kong
      configMap:
        name: kong
  userDefinedVolumeMounts:
    - name: kong
      mountPath: /etc/kong/

env:
  DECLARATIVE_CONFIG: "/etc/kong/kong.yml"

admin:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false

service:
  type: LoadBalancer
  externalIPs:
    - 192.168.30.203

dblessConfig:
  configMap: "kong"

extraConfigMaps:
  - name: kong
    mountPath: /etc/kong/